repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        exclude: (^api/migrations/|app/tests|api/tests)
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: (^api/migrations/|app/tests|api/tests)
