git_sources:
  bitbucket:
    enabled: true
    url: "BITBUCKET_URL"
    type: "bitbucket"
    mode: 'incremental'
    credentials_env:
      username: 'BITBUCKET_ACCESS_USERNAME'
      token: 'BITBUCKET_ACCESS_TOKEN'
    excludes:
      repositories:
    ssh:
      private_key: 'config/id_rsa'
      port: 7999
  github:
    enabled: false
    url: "https://github.com"
    type: "github"
    mode: 'full'
secret_sources:
  hashicorp_vault:
    enabled: true
    url: "VAULT_URL"
    type: "hcVault"
    path: "infra/data"
    auth_method: "approle"
    ca_cert: ca.cert
    excludes:
      - welcome
    credentials_env:
      role_id: 'HC_VAULT_ROLE_ID'
      token: 'HC_VAULT_ACCESS_TOKEN'
notifications:
  permissions: https://DASHBOARD_METABASE_URL
  leak: https://DASHBOARD_METABASE_URL
  compliance: https://DASHBOARD_METABASE_URL
  settings: https://DASHBOARD_METABASE_URL
  email:
    enabled: true
    recipients:
      - michael.atkinson@sicpa.com
  teams:
    enabled: false
fetcher:
  import_repositories: true
best_practices:
  project:
    check_access_to_admin:
      enable: true
      notification: true
    check_default_permissions:
      enable: true
      notification: true
      default_value: NO_ACCESS
    check_no_external_user_as_admin:
      enable: true
      notification: true
    check_number_admin:
      enable: true
      notification: true
      max: 5
    check_permissions_read:
      enable: true
      notification: true
      groups: [ ]
    check_permissions_admin:
      enable: true
      notification: false
      groups:
      forbidden_groups:
    check_permissions_write:
      enable: true
      notification: true
      groups:
  repository:
    check_branch_restriction:
      enable: true
      notification: true
      pull_request_only: true
      fast_forward_only: true
      no_deletes: true
      min_approval: true
    check_access_to_admin:
      enable: true
      notification: true
    check_no_external_user_as_admin:
      enable: true
      notification: true
    check_no_groups:
      enable: true
      notification: true
    check_number_admin:
      enable: true
      notification: true
      max: 5
scanner:
  history: false
  config_file: "app/config/gitleaks.toml"
  ignore:
    files:
      - Podfile.lock
      - test_vectors.rs
    folders:
      - test
      - testCommon
      - __tests__
      - tests
      - site-packages
      - node_modules
      - tutorials
      - notebooks
    extensions:
      - .map
      - .sum
      - .bmp
      - .so
      - .dll
      - .exe
      - .rdl
      - .dat
      - .resx
      - .h
      - .suo
      - .dill
      - .dtsx
      - .csproj
      - .svcinfo
      - .vdproj
      - .msi
      - .jar
      - .xsd
      - .json
  max_clone_time: 60
  last_scan_days: 0
  tmp_secret_file: "/mnt/data/sec"
  tmp_git_folder: "/tmp/"
  report_path: "reports/"