"""empty message

Revision ID: 67f9b196ea3e
Revises: 6023cc04d9d2
Create Date: 2025-11-26 10:50:06.321869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f9b196ea3e'
down_revision = '6023cc04d9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_project', sa.Column('webhooks', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_project', 'webhooks')
    # ### end Alembic commands ###
